<a href="https://colab.research.google.com/github/25wh1a05cf-cloud/NASSCOM/blob/main/WEEK-2/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("------------------------------------")

s1_1 = pd.Series([10, 20, 30, 40, 50])


np_array1_2 = np.random.randint(1, 101, size=(3, 4))


df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("\nSeries:")
print(s1_1)

print("\nNumPy Array:")
print(np_array1_2)

print("\nDataFrame:")
print(df1_3)




dates = pd.date_range(start='2023-01-01', periods=100)

df_sales = pd.DataFrame({
    'Date': dates,
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
    'Sales': np.random.randint(100, 1001, 100).astype(float),
    'Quantity': np.random.randint(1, 11, 100).astype(float)
})


sales_nan_idx = np.random.choice(df_sales.index, 5, replace=False)
df_sales.loc[sales_nan_idx, 'Sales'] = np.nan


qty_nan_idx = np.random.choice(df_sales.index, 3, replace=False)
df_sales.loc[qty_nan_idx, 'Quantity'] = np.nan

print("\nFirst 5 Rows:")
print(df_sales.head())




df3_1 = df_sales[['Region', 'Sales']]


df3_2 = df_sales[df_sales['Product'] == 'Laptop']


df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]


monitor_index = df_sales[df_sales['Product'] == 'Monitor'].index[0]

val3_4 = df_sales.loc[monitor_index, 'Sales']

print("\nRegion and Sales:")
print(df3_1.head())

print("\nLaptop Records:")
print(df3_2.head())

print("\nEast Region with Sales > 500:")
print(df3_3.head())

print("\nFirst Monitor Sales:", val3_4)





missing_counts4_1 = df_sales.isnull().sum()


df4_2_filled = df_sales.copy()

sales_mean = df4_2_filled['Sales'].mean()

df4_2_filled['Sales'].fillna(sales_mean, inplace=True)


df4_3_dropped = df_sales.dropna()

print("\nMissing Values:")
print(missing_counts4_1)

print("\nFilled Data:")
print(df4_2_filled.head())

print("\nDropped Missing Values:")
print(df4_3_dropped.head())



df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']


df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)


df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()


df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("\nData with Total Revenue:")
print(df_sales.head())

print("\nSorted Data:")
print(df5_2_sorted.head())

print("\nGrouped by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)

--- Intermediate Pandas Exercise ---
------------------------------------

Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[76 32 38 15]
 [14 36 67 19]
 [56 55 69 82]]

DataFrame:
    A   B   C   D
0  76  32  38  15
1  14  36  67  19
2  56  55  69  82

First 5 Rows:
        Date Region   Product  Sales  Quantity
0 2023-01-01   East    Laptop  351.0       1.0
1 2023-01-02  North    Laptop  877.0       1.0
2 2023-01-03   West  Keyboard  397.0       9.0
3 2023-01-04   East  Keyboard  386.0       3.0
4 2023-01-05   West  Keyboard  930.0       NaN

Region and Sales:
  Region  Sales
0   East  351.0
1  North  877.0
2   West  397.0
3   East  386.0
4   West  930.0

Laptop Records:
         Date Region Product  Sales  Quantity
0  2023-01-01   East  Laptop  351.0       1.0
1  2023-01-02  North  Laptop  877.0       1.0
8  2023-01-09  South  Laptop  703.0       5.0
9  2023-01-10   West  Laptop  705.0       3.0
13 2023-01-14  North  Laptop  728.0       5.0

East Region wi

/tmp/ipykernel_689/2313233808.py:89: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df4_2_filled['Sales'].fillna(sales_mean, inplace=True)
